# Global Configs
[config]
version_check = false

# Hyprland
[templates.hyprland]
input_path = '~/.config/matugen/templates/matugen-hyprland.conf'
output_path = '~/.config/hypr/matugen/matugen-hyprland.conf'

# Waybar
[templates.waybar]
input_path = '~/.config/matugen/templates/matugen-waybar.css'
output_path = '~/.config/waybar/matugen/matugen-waybar.css'
#post_hook = 'killall -SIGUSR2 waybar'

# Swaync
[templates.swaync]
input_path = '~/.config/matugen/templates/matugen-swaync.css'
output_path = '~/.config/swaync/matugen/matugen-swaync.css'
#post_hook = 'swaync-client -rs'
